variables:
  GIT_STRATEGY: clone
  APP_NAME: zeno-common-client

stages:
  - build
  - test
  - publish

build:
  stage: build
  image: node:alpine
  script:
    - npm ci
    - npm run build

test:
  stage: test
  image: node:alpine
  script:
    - npm ci
    - npm run test:ci
  artifacts:
      when: always
      reports:
        cobertura:
          - ./coverage/clover.xml
        junit:
          - ./junit.xml

lint:
  stage: test
  image: node:alpine
  script:
    - npm ci
    - npm run lint

publish:
  stage: publish
  image: node:alpine
  script:
    - echo '@mark.davison:registry=https://gitlab.markdavison.kiwi/api/v4/projects/${CI_PROJECT_ID}/packages/npm/' >> .npmrc
    - npm config set //gitlab.markdavison.kiwi/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}
    - npm ci
    - npm run build
    - npm publish